### test

POST http://localhost:3000/measurements
content-type: application/json

{ "measurements": { "temperature": "24", "noise": "true", "humidity": "100" } }


### add game

PUT http://localhost:3000/game
content-type: application/json

{ "name": "Chess", "members": 2 }

### take game

POST http://localhost:3000/takeGame/10294
content-type: application/json


### take break
POST http://localhost:3000/takeBreak/10293
content-type: application/json